/**
 * Inline agentmail/*.html into agentmail/compiled.ts so templates.ts
 * (imported by Convex functions, which cannot read the filesystem)
 * stays pure. Run: bun run agentmail:build
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const files = ["magic-link.html", "share-board.html", "custom.html"] as const;

const parts: string[] = [
  "// Generated by agentmail/build.ts — do not edit. Edit the *.html files.",
];
for (const f of files) {
  const html = readFileSync(join(dir, f), "utf8");
  const name = f.replace(/\.html$/, "").replace(/-/g, "_").toUpperCase();
  parts.push(`export const ${name}_HTML = ${JSON.stringify(html)};`);
}
writeFileSync(join(dir, "compiled.ts"), parts.join("\n") + "\n");
console.log("agentmail compiled:", files.join(", "));
