/**
 * Inline agentmail/*.html into agentmail/compiled.ts so templates.ts
 * (imported by Convex functions, which cannot read the filesystem)
 * stays pure. Run: bun run agentmail:build
 */
const files = ["magic-link.html", "share-board.html", "custom.html"] as const;

const parts: string[] = [
  "// Generated by agentmail/build.ts — do not edit. Edit the *.html files.",
];
for (const f of files) {
  const html = await Bun.file(new URL(`./${f}`, import.meta.url)).text();
  const name = f.replace(/\.html$/, "").replace(/-/g, "_").toUpperCase();
  parts.push(`export const ${name}_HTML = ${JSON.stringify(html)};`);
}
await Bun.write(new URL("./compiled.ts", import.meta.url), parts.join("\n") + "\n");
console.log("agentmail compiled:", files.join(", "));
